[build]
builder = "nixpacks"
buildCommand = "pip install -r server/requirements.txt"
startCommand = "python server/server.py"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production.variables]
PORT = "5555"
